# Configuración general
WIDTH = 640
HEIGHT = 480
FPS = 60

# Colores (R, G, B)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)
ORANGE = (255, 165, 0)
CYAN = (0, 255, 255)

# Jugador
PLAYER_SPEED = 300.0
PLAYER_HP = 3
PLAYER_MAX_HP = 3
PLAYER_INVULN_TIME = 1.0

# Capas de renderizado
LAYER_BACKGROUND = 0
LAYER_ENTITIES = 1
LAYER_PROJECTILES = 2
LAYER_PARTICLES = 3
LAYER_UI = 4

# Armas - valores base (se modifican con upgrades)
WEAPON_PISTOL_COOLDOWN = 0.3
WEAPON_PISTOL_DAMAGE = 10
WEAPON_PISTOL_SPREAD = 0.0
WEAPON_PISTOL_PROJECTILE_SPEED = 800.0

WEAPON_SHOTGUN_COOLDOWN = 0.8
WEAPON_SHOTGUN_DAMAGE = 6
WEAPON_SHOTGUN_SPREAD = 0.26  # ~15 grados en radianes
WEAPON_SHOTGUN_PELLETS = 5
WEAPON_SHOTGUN_PROJECTILE_SPEED = 700.0

WEAPON_RIFLE_COOLDOWN = 0.15
WEAPON_RIFLE_DAMAGE = 8
WEAPON_RIFLE_SPREAD = 0.0
WEAPON_RIFLE_PROJECTILE_SPEED = 1000.0
WEAPON_RIFLE_PIERCE = 1

WEAPON_LAUNCHER_COOLDOWN = 1.5
WEAPON_LAUNCHER_DAMAGE = 40
WEAPON_LAUNCHER_EXPLOSION_RADIUS = 60.0
WEAPON_LAUNCHER_PROJECTILE_SPEED = 400.0

# Enemigos base
ENEMY_BASIC_HP = 30
ENEMY_BASIC_SPEED = 80.0
ENEMY_BASIC_DAMAGE = 1
ENEMY_BASIC_GOLD = 10

ENEMY_TANK_HP = 120
ENEMY_TANK_SPEED = 40.0
ENEMY_TANK_DAMAGE = 2
ENEMY_TANK_GOLD = 25
ENEMY_TANK_KNOCKBACK_RESIST = 0.5

ENEMY_SPEEDY_HP = 15
ENEMY_SPEEDY_SPEED = 180.0
ENEMY_SPEEDY_DAMAGE = 1
ENEMY_SPEEDY_GOLD = 15
ENEMY_SPEEDY_DODGE_CHANCE = 0.1

# Barreras
BARRIER_MAX_HP = 200
BARRIER_COST = 50
BARRIER_REPAIR_COST_PER_SEC = 10
BARRIER_REPAIR_HP_PER_SEC = 20
BARRIER_GRID_SIZE = 40

# Economia
STARTING_GOLD = 0
KILL_GOLD_MULTIPLIER = 1.0

# Power-ups
POWERUP_SPAWN_CHANCE = 0.15
POWERUP_DURATION = 5.0
POWERUP_SPEED_MULT = 1.5
POWERUP_DAMAGE_MULT = 2.0
POWERUP_SHIELD_DURATION = 3.0
POWERUP_SLOWMO_MULT = 0.5
POWERUP_SLOWMO_DURATION = 4.0

# Partículas
PARTICLE_POOL_SIZE = 200
PARTICLE_LIFETIME = 0.5

# Screen shake
SCREEN_SHAKE_MAX_INTENSITY = 10.0
